
##Exceptions

###Что такое исключение (Exception) в Java? Как оно отличается от ошибки (Error)?
>Исключение (Exception) в Java - это событие, которое нарушает нормальный поток выполнения программы.   
>Исключения можно обрабатывать в коде с помощью конструкций try-catch.   
>Ошибка (Error) представляет собой более серьезное условие, от которого приложение обычно не может восстановиться,   
>например, OutOfMemoryError. Исключения наследуются от java.lang.Exception, а ошибки - от java.lang.Error.  

###Что такое проверяемые (checked) и непроверяемые (unchecked) исключения? Приведите примеры.
>Проверяемые (checked) исключения являются подклассами Exception (исключая RuntimeException) и должны быть либо пойманы,   
>либо объявлены в сигнатуре метода с помощью throws. **Примеры: IOException, SQLException.**   
> Непроверяемые (unchecked) исключения являются подклассами RuntimeException и не требуют обязательной обработки.    
>**Примеры: NullPointerException, ArrayIndexOutOfBoundsException.**

###Как вы создаете собственное исключение в Java?
>Для создания собственного исключения нужно создать класс, который наследуется от Exception или RuntimeException. 

```java
public class MyCustomException extends Exception {
    public MyCustomException(String message) {
        super(message);
    }
}
```

###Какие ключевые используются для работы с исключениями в Java опишите работу блока try catch finally?
>**Ключевые слова для работы с исключениями в Java:**
>- try: блок кода, который может вызвать исключение.
>- catch: блок кода, который обрабатывает исключение.
>- finally: блок кода, который выполняется независимо от того, произошло исключение или нет.
>- throw: используется для выброса исключения.
>- throws: указывает, что метод может выбросить исключение.



###Что такое блок finally? Всегда ли он выполняется?
>Блок finally используется для выполнения кода, который должен быть выполнен независимо от того,   
>произошло исключение или нет. Обычно он используется для освобождения ресурсов, например, закрытия файлов или сокетов.  
>Блок finally всегда выполняется, за исключением случаев, когда виртуальная машина завершает свою работу или возникает ошибка (Error),  
>которая приводит к аварийному завершению работы программы.

Что вернется если будет выброшено исключение в try или не будет
```java
public int exampleMethod() {
        try {
        // код, который может вызвать исключение   
        } catch (Exception e) {
        return 1; 
        } finally {
        return 2;
        }
}
```

###Объясните, как работает многократный блок catch. В каком порядке они должны быть расположены?

 **Правильно ли расположены исключения в блоках catch ?**
```java
try {
    // код, который может вызвать исключение
} catch (Exception e) {
    
}catch (FileNotFoundException e) {
        
        } 
```
Нет потому что Exception стоит первым и мы некогда не обработаем FileNotFoundException потому что не дойдем до него  

